version: "3.2"

services:
#db
  mysql:
    image: mysql:9
    container_name: mysqldb
    hostname: mysql
    volumes:
      - mysqldb:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always

  glpi:
    image: teste-glpi:1.0
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi-data:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Sao_Paulo
    restart: always

volumes:
  mysqldb:
  glpi-data: