version: "3.2"

services:
#db
  mysql:
    image: mysql:9
    container_name: mysqldb
    hostname: mysql
    volumes:
      - mysqldb:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  glpi:
    image: iagorml/glpi:${GLPI_VERSION}
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - glpi-data:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Sao_Paulo
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  mysqldb:
  glpi-data: